FROM envoyproxy/envoy-alpine-dev:latest

COPY ./front-envoy-skywalking.yaml /etc/front-envoy.yaml
COPY envoy-static /usr/local/bin/envoy
RUN chmod go+r /etc/front-envoy.yaml
CMD /usr/local/bin/envoy -l trace -c /etc/front-envoy.yaml --service-cluster front-proxy
